#python run_tests.py --output results/schoopy --json_name 07 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --test_iterations 10 11 12 13 14 15 16 --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_07.pth
#python run_tests.py --output results/schoopy --json_name 14 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --test_iterations 10 11 12 13 14 15 16 --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_14.pth
#python run_tests.py --output results/schoopy --json_name 15 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --test_iterations 10 11 12 13 14 15 16 --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_15.pth
#python run_tests.py --output results/schoopy --json_name 17 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --test_iterations 10 11 12 13 14 15 16 --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_17.pth
#python run_tests.py --output results/schoopy --json_name 18 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --test_iterations 10 11 12 13 14 15 16 --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_18.pth
#
#python run_tests.py --output results/schoopy --json_name 07 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --test_iterations 10 11 12 13 14 15 16 --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_07.pth
#python run_tests.py --output results/schoopy --json_name 14 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --test_iterations 10 11 12 13 14 15 16 --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_14.pth
#python run_tests.py --output results/schoopy --json_name 15 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --test_iterations 10 11 12 13 14 15 16 --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_15.pth
#python run_tests.py --output results/schoopy --json_name 17 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --test_iterations 10 11 12 13 14 15 16 --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_17.pth
#python run_tests.py --output results/schoopy --json_name 18 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --test_iterations 10 11 12 13 14 15 16 --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_18.pth
#
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 01 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_01.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 02 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_02.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 03 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_03.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 04 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_04.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 05 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_05.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 06 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_06.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 07 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_07.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 08 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_08.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 09 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_09.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 10 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_10.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 11 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_11.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 12 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_12.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 13 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_13.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 14 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_14.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 15 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_15.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 16 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_16.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 17 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_17.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 18 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_18.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 19 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_19.pth
#python run_tests.py --output results/fixed_effective_depth_max_conf --json_name 20 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --test_iterations 11  --test_mode max_conf --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_20.pth

#python run_tests.py --output results/fixed_effective_depth_default --json_name 01 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_01.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 02 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_02.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 03 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_03.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 04 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_04.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 05 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_05.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 06 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_06.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 07 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_07.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 08 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_08.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 09 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_09.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 10 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_10.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 11 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_11.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 12 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_12.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 13 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_13.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 14 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_14.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 15 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_15.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 16 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_16.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 17 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_17.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 18 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_18.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 19 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_19.pth --test_iterations 9
#python run_tests.py --output results/fixed_effective_depth_default --json_name 20 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d40_20.pth --test_iterations 9
#
#python run_tests.py --output results/fixed_effective_depth_default --json_name 01 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_01.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 02 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_02.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 03 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_03.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 04 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_04.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 05 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_05.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 06 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_06.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 07 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_07.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 08 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_08.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 09 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_09.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 10 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_10.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 11 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_11.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 12 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_12.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 13 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_13.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 14 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_14.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 15 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_15.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 16 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_16.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 17 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_17.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 18 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_18.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 19 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_19.pth --test_iterations 10
#python run_tests.py --output results/fixed_effective_depth_default --json_name 20 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d44_20.pth --test_iterations 10
#
#python run_tests.py --output results/fixed_effective_depth_default --json_name 01 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_01.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 02 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_02.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 03 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_03.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 04 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_04.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 05 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_05.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 06 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_06.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 07 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_07.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 08 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_08.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 09 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_09.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 10 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_10.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 11 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_11.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 12 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_12.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 13 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_13.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 14 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_14.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 15 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_15.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 16 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_16.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 17 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_17.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 18 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_18.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 19 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_19.pth --test_iterations 11
#python run_tests.py --output results/fixed_effective_depth_default --json_name 20 --train_batch_size 300 --test_batch_size 300 --model recur_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/recur_net_d48_20.pth --test_iterations 11

#python run_tests.py --output results/schoopy_ff --json_name 01 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_01.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 02 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_02.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 03 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_03.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 04 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_04.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 05 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_05.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 06 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_06.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 07 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_07.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 08 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_08.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 09 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_09.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 10 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_10.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 11 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_11.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 12 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_12.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 13 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_13.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 14 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_14.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 15 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_15.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 16 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_16.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 17 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_17.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 18 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_18.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 19 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_19.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 20 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 40 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d40_20.pth --test_iterations -1
#
#python run_tests.py --output results/schoopy_ff --json_name 01 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_01.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 02 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_02.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 03 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_03.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 04 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_04.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 05 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_05.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 06 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_06.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 07 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_07.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 08 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_08.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 09 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_09.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 10 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_10.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 11 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_11.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 12 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_12.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 13 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_13.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 14 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_14.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 15 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_15.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 16 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_16.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 17 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_17.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 18 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_18.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 19 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_19.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 20 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 44 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d44_20.pth --test_iterations -1
#
#python run_tests.py --output results/schoopy_ff --json_name 01 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_01.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 02 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_02.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 03 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_03.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 04 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_04.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 05 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_05.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 06 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_06.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 07 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_07.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 08 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_08.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 09 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_09.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 10 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_10.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 11 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_11.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 12 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_12.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 13 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_13.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 14 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_14.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 15 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_15.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 16 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_16.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 17 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_17.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 18 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_18.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 19 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_19.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 20 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 48 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d48_20.pth --test_iterations -1
#
#python run_tests.py --output results/schoopy_ff --json_name 01 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_01.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 02 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_02.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 03 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_03.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 04 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_04.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 05 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_05.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 06 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_06.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 07 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_07.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 08 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_08.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 09 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_09.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 10 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_10.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 11 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_11.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 12 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_12.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 13 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_13.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 14 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_14.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 15 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_15.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 16 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_16.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 17 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_17.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 18 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_18.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 19 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_19.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 20 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 52 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d52_20.pth --test_iterations -1
#
#python run_tests.py --output results/schoopy_ff --json_name 01 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_01.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 02 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_02.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 03 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_03.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 04 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_04.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 05 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_05.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 06 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_06.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 07 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_07.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 08 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_08.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 09 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_09.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 10 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_10.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 11 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_11.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 12 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_12.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 13 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_13.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 14 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_14.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 15 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_15.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 16 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_16.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 17 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_17.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 18 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_18.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 19 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_19.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 20 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 56 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d56_20.pth --test_iterations -1
#
#python run_tests.py --output results/schoopy_ff --json_name 01 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_01.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 02 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_02.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 03 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_03.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 04 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_04.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 05 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_05.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 06 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_06.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 07 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_07.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 08 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_08.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 09 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_09.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 10 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_10.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 11 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_11.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 12 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_12.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 13 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_13.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 14 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_14.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 15 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_15.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 16 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_16.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 17 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_17.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 18 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_18.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 19 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_19.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 20 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 60 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d60_20.pth --test_iterations -1
#
#python run_tests.py --output results/schoopy_ff --json_name 01 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_01.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 02 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_02.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 03 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_03.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 04 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_04.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 05 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_05.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 06 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_06.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 07 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_07.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 08 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_08.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 09 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_09.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 10 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_10.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 11 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_11.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 12 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_12.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 13 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_13.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 14 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_14.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 15 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_15.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 16 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_16.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 17 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_17.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 18 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_18.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 19 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_19.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 20 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 64 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/for_paper/ff_net_d64_20.pth --test_iterations -1
#
#python run_tests.py --output results/schoopy_ff --json_name 01 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_01.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 02 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_02.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 03 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_03.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 04 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_04.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 05 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_05.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 06 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_06.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 07 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_07.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 08 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_08.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 09 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_09.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 10 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_10.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 11 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_11.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 12 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_12.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 13 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_13.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 14 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_14.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 15 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_15.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 16 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_16.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 17 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_17.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 18 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_18.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 19 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_19.pth --test_iterations -1
#python run_tests.py --output results/schoopy_ff --json_name 20 --train_batch_size 300 --test_batch_size 300 --model ff_net --depth 68 --train_data 32 --eval_data 44 --width 120 --model_path /cmlscratch/eborgnia/parity/checkpoints/training_32_paper/ff_net_adam_depth=68_width=120_lr=0.001_batchsize=150_epoch=499_20.pth --test_iterations -1
